import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache resources generated by build
precacheAndRoute(self.__WB_MANIFEST);

// Cache API calls (Offline Mode - Improvement 5)
// Profile & History: StaleWhileRevalidate (Show cached, then update)
registerRoute(
    ({ url }) => url.pathname.includes('/api/viajes/historial') || url.pathname.includes('/api/perfil'),
    new StaleWhileRevalidate({
        cacheName: 'api-data-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 24 * 60 * 60, // 1 day
            }),
        ],
    })
);

// Map Tiles: Cache heavily
registerRoute(
    ({ url }) => url.host.includes('openstreetmap.org'),
    new StaleWhileRevalidate({
        cacheName: 'map-tiles',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 1000,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Push Notifications (Improvement 4)
self.addEventListener('push', (event) => {
    let data = { title: 'MotoTX', body: 'Nueva notificación' };

    if (event.data) {
        try {
            data = event.data.json();
        } catch (e) {
            data.body = event.data.text();
        }
    }

    const options = {
        body: data.body,
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        vibrate: [100, 50, 100],
        data: {
            url: data.url || '/'
        }
    };

    event.waitUntil(
        self.registration.showNotification(data.title, options)
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        clients.openWindow(event.notification.data.url)
    );
});
